export const ENDPOINTS = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    me: "/auth/me",
    register: "/auth/register",
    refresh: "/auth/refresh",
    activate: "/auth/activate",
    activateValidate: "/auth/activate/validate",
    activateResend: "/auth/activate/resend",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    resetPasswordValidate: "/auth/reset-password/validate",
    resetPasswordResend: "/auth/reset-password/resend",
    resendWelcome: (id: string) => `/admin/users/${id}/resend-invitation`,
  },
  student: {
    profile: "/student/profile",
    dashboard: "/dashboard/student",
  },
  guide: {
    profile: "/guide/profile",
    dashboard: "/dashboard/guide",
  },
  reviews: {
    my: "/reviews/my",
    project: (id: string) => `/reviews/project/${id}`,
  },
  chapters: {
    list: (id: string) => `/projects/${id}/chapters`,
    detail: (id: string) => `/chapters/${id}`,
    status: (id: string) => `/chapters/${id}/status`,
    comments: {
      list: (id: string) => `/chapters/${id}/comments`,
      add: (id: string) => `/chapters/${id}/comments`,
      delete: (chapterId: string, commentId: string) => `/chapters/${chapterId}/comments/${commentId}`,
    },
  },
  approvalHistory: {
    project: (id: string) => `/approval-history/project/${id}`,
    chapter: (id: string) => `/approval-history/chapter/${id}`,
  },
  projects: {
    list: "/projects/my",
    detail: (id: string) => `/projects/${id}`,
    members: {
      add: (id: string) => `/projects/${id}/members`,
      remove: (id: string, memberId: string) => `/projects/${id}/members/${memberId}`,
    },
    tasks: {
      list: (id: string) => `/projects/${id}/tasks`,
      detail: (projectId: string, taskId: string) => `/projects/${projectId}/tasks/${taskId}`,
    },
    milestones: {
      list: (id: string) => `/projects/${id}/milestones`,
      detail: (projectId: string, milestoneId: string) => `/projects/${projectId}/milestones/${milestoneId}`,
    },
    documents: {
      list: (id: string) => `/projects/${id}/documents`,
      detail: (projectId: string, docId: string) => `/projects/${projectId}/documents/${docId}`,
    },
  },
  notifications: {
    list: "/notifications",
    unreadCount: "/notifications/unread-count",
    markRead: "/notifications/mark-read",
    markAllRead: "/notifications/mark-all-read",
  },
  students: {
    list: "/students",
    detail: (id: string) => `/students/${id}`,
  },
  guides: {
    list: "/guides",
    detail: (id: string) => `/guides/${id}`,
  },
  research: {
    list: "/research",
    detail: (id: string) => `/research/${id}`,
    chapters: (id: string) => `/research/${id}/chapters`,
  },
  meetings: {
    list: "/meetings",
    detail: (id: string) => `/meetings/${id}`,
  },
  hod: {
    profile: "/hod/profile",
    dashboard: "/hod/dashboard",
    students: "/hod/students",
    guides: "/hod/guides",
    guidesAssign: "/hod/guides/assign",
    allocations: "/hod/allocations",
    researchCategories: "/hod/research-categories",
    researchTopics: "/hod/research-topics",
    announcements: "/hod/announcements",
    announcementsPublish: (id: string) => `/hod/announcements/${id}/publish`,
    announcementsExpire: (id: string) => `/hod/announcements/${id}/expire`,
    reports: "/hod/reports",
    reportsGenerate: "/hod/reports/generate",
  },
  ai: {
    chat: "/ai/chat",
    stream: "/ai/stream",
    providers: "/ai/providers",
  },
  admin: {
    dashboard: "/admin/dashboard",
    colleges: "/admin/colleges",
    collegeDetail: (id: string) => `/admin/colleges/${id}`,
    departments: "/admin/departments",
    departmentDetail: (id: string) => `/admin/departments/${id}`,
    academicYears: "/admin/academic-years",
    academicYearDetail: (id: string) => `/admin/academic-years/${id}`,
    academicYearSetCurrent: (id: string) => `/admin/academic-years/${id}/set-current`,
    semesters: "/admin/semesters",
    semesterDetail: (id: string) => `/admin/semesters/${id}`,
    semestersByAcademicYear: (id: string) => `/admin/semesters/by-academic-year/${id}`,
    semesterSetCurrent: (id: string) => `/admin/semesters/${id}/set-current`,
    faculties: "/admin/faculties",
    facultyDetail: (id: string) => `/admin/faculties/${id}`,
    users: "/admin/users",
    userDetail: (id: string) => `/admin/users/${id}`,
    roles: "/admin/roles",
    roleDetail: (id: string) => `/admin/roles/${id}`,
    permissions: "/admin/permissions",
    permissionDetail: (id: string) => `/admin/permissions/${id}`,
    announcements: "/admin/announcements",
    announcementDetail: (id: string) => `/admin/announcements/${id}`,
    announcementPublish: (id: string) => `/admin/announcements/${id}/publish`,
    auditLogs: "/admin/audit-logs",
    auditLogDetail: (id: string) => `/admin/audit-logs/${id}`,
    settings: "/admin/settings",
    settingDetail: (id: string) => `/admin/settings/${id}`,
    settingByKey: (key: string) => `/admin/settings/by-key/${key}`,
  },
} as const;
